# Chapter 5.  Getting Started with pandas

* Pandas contains data structures and data manipulation tools designed to make data cleaning
and analysis fast and easy in Python. 
* Pandas is often used in tandem with numerical
computing tools like NumPy and SciPy, analytical libraries like statsmodels and
scikit-learn, and data visualization libraries like matplotlib. 
* Pandas adopts significant
parts of NumPy’s idiomatic style of array-based computing, especially array-based
functions and a preference for data processing without for loops.
* While pandas adopts many coding idioms from NumPy, the biggest difference is that
pandas is designed for working with tabular or heterogeneous data. 
* NumPy, by contrast, is best suited for working with homogeneous numerical array data.

In [1]:
import pandas as pd

<span style="color:red">Thus, whenever you see **pd.** in code, it’s referring to pandas.

In [2]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## 5.1  Introduction to pandas Data Structures

There are two core objects in pandas: the **DataFrame** and the **Series**.  
While they are not a universal solution for every problem, they provide a solid, easy-to-use basis for most applications.

## The pandas data structures: `DataFrame` and `Series`

A `DataFrame` is a **tablular data structure** (multi-dimensional object to hold labeled data) comprised of rows and columns, akin to a spreadsheet, database table, or R's data.frame object. You can think of it as multiple Series object which share the same index.

<img align="left" width=50% src="pic/pic_5_02.png">      
<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
    
<img align="left" width=50% src="pic/pic_5_01.png">

### DataFrame

A DataFrame is a table.   

For example, consider the following simple DataFrame:

In [3]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In this example, the "0, No" entry has the value of 131.   
The "0, Yes" entry has a value of 50, and so on.

DataFrame entries are not limited to integers.   
For instance, here's a DataFrame whose values are strings:

In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

We are using the pd.DataFrame() constructor to generate these DataFrame objects.   
The syntax for declaring a new one is a dictionary whose keys are the column names (Bob and Sue in this example), and whose values are a list of entries.   
This is the standard way of constructing a new DataFrame, and the one you are most likely to encounter.

The dictionary-list constructor assigns values to the column labels, but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the row labels.   
Sometimes this is OK, but oftentimes we will want to assign these labels ourselves.

The list of row labels used in a DataFrame is known as an Index.   
We can assign values to it by using an index parameter in our constructor:

In [5]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

### Series

A Series is a sequence of data values.   
If a DataFrame is a table, a Series is a list.   
And in fact you can create one with nothing more than a list:

In [6]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

A Series is, in essence, a single column of a DataFrame.   
So you can assign column values to the Series the same way as before, using an index parameter.   
However, a Series does not have a column name, it only has one overall name:

In [7]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

The Series and the DataFrame are intimately related.   
It's helpful to think of a DataFrame as actually being just a bunch of Series "glued together".

연습문제 5-1: create a DataFrame `fruits` that looks like this:

<img align="left" src="pic/pic_5_10.png" width=30% >

In [8]:
pd.DataFrame({'Apple':[30], 'Bananas':[21]})

   Apple  Bananas
0     30       21

연습문제 5-2: Create a dataframe `fruit_sales` that matches the diagram below:

<img align="left" src="pic/pic_5_11.png" width=30% >

연습문제 5-3: Create a variable `ingredients` with a Series that looks like:

<img align="left" src="pic/pic_5_12.png" width=30% >

### Series

* A Series is a one-dimensional array-like object containing a sequence of values (of
similar types to NumPy types) and an associated array of data labels, called its *index*.
* The simplest Series is formed from only an array of data:

In [9]:
obj = pd.Series([4, 7, -5, 3])

In [10]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [11]:
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64

* The print representation of a Series displayed interactively shows the index on the
left and the values on the right. 
* Since we did not specify an index for the data, a
default one consisting of the integers 0 through N - 1 (where N is the length of the
data) is created. 
* You can get the array representation and index object of the Series via
its values and index attributes, respectively:

In [12]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [13]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

* Often it will be desirable to create a Series with an index identifying each data point
with a label.

In [14]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [15]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

* Compared with NumPy arrays, you can use labels in the index when selecting single
values or a set of values.

In [17]:
obj2['a']

-5

In [18]:
obj2['d'] = 6

In [19]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [20]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

* Using NumPy functions or NumPy-like operations, such as filtering with a boolean
array, scalar multiplication, or applying math functions, will preserve the index-value
link.

In [21]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [22]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [23]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [24]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

* Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping of index values to data values. 
* It can be used in many contexts where you might
use a dict.

In [25]:
'b' in obj2

True

In [26]:
'e' in obj2

False

* Should you have data contained in a Python dict, you can create a Series from it by
passing the dict.

In [27]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [28]:
obj3 = pd.Series(sdata)

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

* When you are only passing a dict, the index in the resulting Series will have the dict’s
keys in sorted order. 
* You can override this by passing the dict keys in the order you
want them to appear in the resulting Series.

In [30]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [31]:
obj4 = pd.Series(sdata, index=states)

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

* Here, three values found in sdata were placed in the appropriate locations, but since
no value for 'California' was found, it appears as *NaN* (not a number), which is considered in pandas to mark missing or NA values.   
* Since 'Utah' was not included in
states, it is excluded from the resulting object.

* I will use the terms “missing” or “NA” interchangeably to refer to missing data. 
* The **isnull** and **notnull** functions in pandas should be used to detect missing data.

In [33]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

* I discuss working with missing data in more detail in Chapter 7.  


* A useful Series feature for many applications is that it automatically aligns by index
label in arithmetic operations.

In [36]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [37]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

* Data alignment features will be addressed in more detail later. 
* If you have experience
with databases, you can think about this as being similar to a join operation.


* Both the Series object itself and its index have a name attribute, which integrates with
other key areas of pandas functionality.

In [39]:
obj4.name = 'population'

In [40]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

The name argument allows you to give a name to a Series object, i.e. to the column. So that when you'll put that in a DataFrame, the column will be named according to the name parameter.

In [41]:
pd.DataFrame(obj4)

            population
California         NaN
Ohio           35000.0
Oregon         16000.0
Texas          71000.0

In [42]:
pd.DataFrame(obj3) #column name이 어떻게 되는지 살펴보자

            0
Ohio    35000
Texas   71000
Oregon  16000
Utah     5000

In [43]:
obj4.index.name = 'state'

In [44]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

A Series’s index can be altered in-place by assignment.

In [45]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [46]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [47]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

<img style="float: left;" src="pic/fig_00.png" width="400">

### DataFrame

* A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string,
boolean, etc.). 
* The DataFrame has both a row and column index; it can be thought of
as a dict of Series all sharing the same index. 
* Under the hood, the data is stored as one
or more two-dimensional blocks rather than a list, dict, or some other collection of
one-dimensional arrays. 
* The exact details of DataFrame’s internals are outside the
scope of this book.

<img style="float: left;" src="pic/pic_0_2.png">

While a DataFrame is physically two-dimensional, you can use it to
represent higher dimensional data in a tabular format using hierarchical indexing,
a subject we will discuss in Chapter 8 and an
ingredient in some of the more advanced data-handling features in pandas.

There are many ways to construct a DataFrame, though one of the most common is
from a dict of equal-length lists or NumPy arrays.

In [48]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [49]:
df = pd.DataFrame(data)

The resulting DataFrame will have its index assigned automatically as with Series, and
the columns are placed in sorted order.

In [50]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [51]:
type(df)

pandas.core.frame.DataFrame

In [52]:
type(obj4)

pandas.core.series.Series

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   6 non-null      object
 1   year    6 non-null      int64
 2   pop     6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 272.0+ bytes

If you are using the Jupyter notebook, pandas DataFrame objects will be displayed as
a more browser-friendly HTML table.


For large DataFrames, the **head** method selects only the first five rows.

In [54]:
df.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

If you specify a sequence of columns, the DataFrame’s columns will be arranged in
that order.

In [55]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

If you pass a column that isn’t contained in the dict, it will appear with missing values
in the result.

In [56]:
df2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])

In [57]:
df2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [58]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

A column in a DataFrame can be retrieved as a Series either by dict-like notation or
by attribute.

In [59]:
df2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [60]:
df2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [61]:
type(df2.year)

pandas.core.series.Series

<img style="float: left;" src="pic/pic_0_2.png">

Attribute-like access (e.g., df2.year) and tab completion of column names in IPython is provided as a convenience.

df2[column] works for any column name, but df2.column
only works when the column name is a valid Python variable
name.
<br><br><br>

Rows can also be retrieved by position or name with the special loc attribute (much
more on this later).

In [62]:
df2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

Columns can be modified by assignment. For example, the empty 'debt' column
could be assigned a scalar value or an array of values.

In [63]:
df2['debt'] = 16.5

In [64]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [65]:
df2['debt'] = np.arange(6.)

In [66]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value’s length must match the
length of the DataFrame.   
If you assign a Series, its labels will be realigned exactly to
the DataFrame’s index, inserting missing values in any holes.

In [67]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [68]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [69]:
df2['debt'] = val

In [70]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

Assigning a column that doesn’t exist will create a new column.   
The **del** keyword will
delete columns as with a dict.  

As an example of **del**, I first add a new column of boolean values where the state
column equals 'Ohio'.

In [71]:
df2['eastern'] = df2.state == 'Ohio'

In [72]:
df2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

<img style="float: left;" src="pic/pic_0_1.png">

<span style="color:red">New columns cannot be created with the df2.western syntax.

In [73]:
df2.western= df2.state == 'Ohio'

C:\Users\NN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.

In [74]:
df2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

The **del** method can then be used to remove this column.

In [75]:
del df2['eastern']

In [76]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [77]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

<img style="float: left;" src="pic/pic_0_1.png">

<span style="color:red">The column returned from indexing a DataFrame is a view on the
underlying data, not a copy. Thus, any in-place modifications to the
Series will be reflected in the DataFrame. The column can be
explicitly copied with the Series’s copy method.

In [78]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [79]:
aaa=df2['debt']

In [80]:
aaa

one      NaN
two     -1.2
three    NaN
four    -1.5
five    -1.7
six      NaN
Name: debt, dtype: float64

In [81]:
aaa['one']=1.5

C:\Users\NN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [82]:
aaa

one      1.5
two     -1.2
three    NaN
four    -1.5
five    -1.7
six      NaN
Name: debt, dtype: float64

In [83]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

copy()를 사용해보자.

In [84]:
bbb=df2['pop'].copy()

In [85]:
bbb

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [86]:
bbb['one']=5

In [87]:
bbb

one      5.0
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [88]:
df2

       year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

Another common form of data is a nested dict of dicts.

In [89]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [90]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

If the nested dict is passed to the DataFrame, pandas will interpret the outer dict keys
as the columns and the inner keys as the row indices.

In [91]:
df3 = pd.DataFrame(pop)

In [92]:
df3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

You can transpose the DataFrame (swap rows and columns) with similar syntax to a
NumPy array.

In [93]:
df3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

The keys in the inner dicts are combined and sorted to form the index in the result.  
This isn’t true if an explicit index is specified.

In [94]:
pd.DataFrame(pop)

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [95]:
pd.__version__

'1.3.4'

<img style="float: left;" src="pic/pic_0_1.png">

<span style="color:red"> **만일 pandas 가 0.23 버전 또는 그 이하이면 업데이트 해야 한다.   
현재 jupyter notebook을 모두 kill 한 후, anaconda prompt 창으로 가서 conda update pandas 를 실행하라.**

In [96]:
pd.DataFrame(pop,index=[2001,2002,2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

Dicts of Series are treated in much the same way.

In [97]:
df3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [98]:
pdata = {'Ohio': df3['Ohio'][:-1],
         'Nevada': df3['Nevada'][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

<img style="float: left;" src="pic/pic_5_1.png" width="700">

If a DataFrame’s index and columns have their name attributes set, these will also be
displayed.

In [99]:
df3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [100]:
df3.index.name = 'year'; df3.columns.name = 'state'

In [101]:
df3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

As with Series, the values attribute returns the data contained in the DataFrame as a
two-dimensional ndarray.

In [102]:
df3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

If the DataFrame’s columns are different dtypes, the dtype of the values array will be
chosen to accommodate all of the columns.

In [103]:
df2.values

array([[2000, 'Ohio', 1.5, 1.5],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

* pandas’s Index objects are responsible for holding the axis labels and other metadata
(like the axis name or names). 
* Any array or other sequence of labels you use when
constructing a Series or DataFrame is internally converted to an Index.

In [104]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [105]:
obj

a    0
b    1
c    2
dtype: int64

In [106]:
idx = obj.index

In [107]:
idx

Index(['a', 'b', 'c'], dtype='object')

In [108]:
idx[1:]

Index(['b', 'c'], dtype='object')

Index objects are immutable and thus can’t be modified by the user.

In [109]:
idx[1] = 'd'  # TypeError

TypeError: Index does not support mutable operations

Immutability makes it safer to share Index objects among data structures.

In [110]:
labels = pd.Index(np.arange(3))

In [111]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [112]:
obj2 = pd.DataFrame([1.5, -2.5, 0], index=labels)

In [113]:
obj2

     0
0  1.5
1 -2.5
2  0.0

In [114]:
obj2.index is labels

True

<img style="float: left;" src="pic/pic_0_1.png">

<span style="color:red"> Some users will not often take advantage of the capabilities provided by indexes, but because some operations will yield results
containing indexed data, it’s important to understand how they
work.

In addition to being array-like, an Index also behaves like a fixed-size set.

In [115]:
df3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [116]:
df3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [117]:
'Ohio' in df3.columns

True

In [118]:
2003 in df3.index

False

Unlike Python sets, a pandas Index can contain duplicate labels.

In [119]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [120]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [121]:
obj4 = pd.DataFrame([1.5, -2.5, 0, 5], index=dup_labels)
obj4

       0
foo  1.5
foo -2.5
bar  0.0
bar  5.0

In [122]:
obj4.T

   foo  foo  bar  bar
0  1.5 -2.5  0.0  5.0

In [123]:
obj4.loc['foo']

       0
foo  1.5
foo -2.5

## 5.2  Essential Functionality

In [124]:
import pandas as pd
import numpy as np

This section will walk you through the fundamental mechanics of interacting with the
data contained in a Series or DataFrame. In the chapters to come, we will delve more
deeply into data analysis and manipulation topics using pandas. This book is not
intended to serve as exhaustive documentation for the pandas library; instead, we’ll
focus on the most important features, leaving the less common (i.e., more esoteric)
things for you to explore on your own.

### Reindexing

* An important method on pandas objects is **reindex**, which means to create a new
object with the data conformed to a new index. Consider an example.

In [125]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [126]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Calling **reindex** on this Series rearranges the data according to the new index, introducing missing values if any index values were not already present.

In [127]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [128]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

* For ordered data like time series, it may be desirable to do some interpolation or filling of values when reindexing. 
* The **method** option allows us to do this, using a
method such as **ffill**, which forward-fills the values.

In [129]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [130]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [131]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

* With DataFrame, **reindex** can alter either the (row) index, columns, or both. 
* When
passed only a sequence, it reindexes the rows in the result.

In [132]:
df = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [133]:
df

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [134]:
df2 = df.reindex(['a', 'b', 'c', 'd'])

In [135]:
df2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

The columns can be reindexed with the **columns** keyword.

In [136]:
states = ['Texas', 'Utah', 'California']

In [137]:
df.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

<img style="float: left;" src="pic/pic_5_2.png" width="700">

In [138]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [139]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [140]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [141]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [142]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [143]:
obj3.reindex(range(6), fill_value='???')

0      blue
1       ???
2    purple
3       ???
4    yellow
5       ???
dtype: object

As we’ll explore in more detail, you can reindex more succinctly by label-indexing
with **loc**, and many users prefer to use it exclusively.

아래 코드는 오류가 남

In [ ]:
#df.loc[['a', 'b', 'c', 'd'], states]

### Dropping Entries from an Axis

* Dropping one or more entries from an axis is easy if you already have an index array
or list without those entries. 
* As that can require a bit of munging and set logic, the **drop** method will return a new object with the indicated value or values deleted from
an axis.

In [144]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [145]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [146]:
new_obj = obj.drop('c')

In [147]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [148]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [149]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [150]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

* With DataFrame, index values can be deleted from either axis. To illustrate this, we
first create an example DataFrame.

In [151]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [152]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Calling **drop** with a sequence of labels will drop values from the row labels (axis 0).

In [153]:
data.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* You can drop values from the columns by passing axis=1 or axis='columns'.

In [155]:
data.drop('two', axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [156]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [157]:
data.drop(['two', 'four'], axis='columns')

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [158]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Many functions, like **drop**, which modify the size or shape of a Series or DataFrame,
can manipulate an object in-place without returning a new object.

In [159]:
data.drop('Ohio', inplace=True)

In [160]:
data

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Indexing, Selection, and Filtering

Series indexing (obj[...]) works analogously to NumPy array indexing, except you
can use the Series’s index values instead of only integers. Here are some examples of
this:

In [161]:
obj = pd.Series(np.arange(5,9), index=['a', 'b', 'c', 'd'])

In [162]:
obj

a    5
b    6
c    7
d    8
dtype: int32

In [163]:
obj['b']

6

In [164]:
obj[1]

6

In [165]:
obj[2:4]

c    7
d    8
dtype: int32

In [166]:
obj[['b', 'a', 'd']]

b    6
a    5
d    8
dtype: int32

In [167]:
obj[[1, 3]]

b    6
d    8
dtype: int32

In [168]:
obj[obj < 7]

a    5
b    6
dtype: int32

### <span style="color:red"> Slicing with labels behaves differently than normal Python slicing in that the endpoint is inclusive.

In [169]:
obj['b':'c']

b    6
c    7
dtype: int32

### <span style="color:red"> But slicing with index numbers behaves like normal Python slicing.

In [170]:
obj[1:3]

b    6
c    7
dtype: int32

Setting using these methods modifies the corresponding section of the Series.

In [171]:
obj['b':'c'] = 15
obj

a     5
b    15
c    15
d     8
dtype: int32

* column retrieving

In [172]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [173]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [174]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [175]:
data[['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

* Indexing like this has a few special cases. First, slicing or selecting data with a boolean
array.

In [176]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [177]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [178]:
data[data['three'] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* The row selection syntax data[:2] is provided as a convenience. 
* Passing a single element or a list to the [ ] operator selects rows.


* Another use case is in indexing with a boolean DataFrame, such as one produced by a
scalar comparison:

In [179]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [180]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [181]:
data[data < 5] = 0

In [182]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

* For DataFrame label-indexing on the rows, I introduce the special indexing operators **loc** and **iloc**. 
* They enable you to select a subset of the rows and columns from a
DataFrame with NumPy-like notation using either axis labels (**loc**) or integers
(**iloc**).

As a preliminary example, let’s select a single row and multiple columns by label

In [183]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [184]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

We’ll then perform some similar selections with integers using **iloc**

In [185]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [186]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [187]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [188]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [189]:
data[2]

KeyError: 2

In [191]:
data[2:3]

      one  two  three  four
Utah    8    9     10    11

In [192]:
data[2:3].values  #pandas

array([[ 8,  9, 10, 11]])

In [198]:
type(data[2:3].values)

numpy.ndarray

In [199]:
data[2:3].values.shape  #pandas

(1, 4)

In [200]:
type(data[2:3])

pandas.core.frame.DataFrame

In [201]:
data.iloc[2].values #series

array([ 8,  9, 10, 11])

In [202]:
data.iloc[2].values.shape

(4,)

In [203]:
type(data.iloc[2])

pandas.core.series.Series

In [204]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [205]:
type(data.iloc[[1, 2], [3, 0, 1]])

pandas.core.frame.DataFrame

In [206]:
data.iloc[[1, 2], [3, 0, 1]].values

array([[ 7,  0,  5],
       [11,  8,  9]])

Both indexing functions work with slices in addition to single labels or lists of labels.

In [207]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [208]:
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

<img style="float: left;" src="pic/pic_5_3.png" width="700">

<img style="float: left;" src="pic/pic_5_4.png" width="700">

### Integer Indexes

* Working with pandas objects indexed by integers is something that often trips up
new users due to some differences with indexing semantics on built-in Python data
structures like lists and tuples. 
* For example, you might not expect the following code
to generate an error.

In [209]:
ser = pd.Series(np.arange(3.))

In [210]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [211]:
ser[-1]

KeyError: -1

On the other hand, with a non-integer index, there is no potential for ambiguity.

In [212]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [213]:
ser2[-1]

2.0

To keep things consistent, if you have an axis index containing integers, data selection
will always be label-oriented.   
For more precise handling, use **loc** (for labels) or **iloc**
(for integers):

In [214]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [215]:
ser[:1]

0    0.0
dtype: float64

In [216]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [217]:
ser2.loc[:'b']

a    0.0
b    1.0
dtype: float64

In [218]:
ser.loc[1]

1.0

In [219]:
ser.iloc[:1]

0    0.0
dtype: float64

In [220]:
ser.iloc[1]

1.0

### Arithmetic and Data Alignment

* An important pandas feature for some applications is the behavior of arithmetic
between objects with different indexes. 
* When you are adding together objects, if any
index pairs are not the same, the respective index in the result will be the union of the
index pairs. 
* For users with database experience, this is similar to an automatic outer
join on the index labels. Let’s look at an example:

In [221]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [222]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [223]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [224]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

Adding these together yields.

In [225]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

* The internal data alignment introduces missing values in the label locations that don’t
overlap.
* Missing values will then propagate in further arithmetic computations.


* In the case of DataFrame, alignment is performed on both the rows and the columns:

In [226]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [227]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [228]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [229]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

* Adding these together returns a DataFrame whose index and columns are the unions
of the ones in each DataFrame.

In [230]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

* Since the 'c' and 'e' columns are not found in both DataFrame objects, they appear
as all missing in the result. 
* The same holds for the rows whose labels are not common
to both objects.


* If you add DataFrame objects with no column or row labels in common, the result
will contain all nulls:

In [231]:
df1 = pd.DataFrame({'A': [1, 2]})

In [232]:
df2 = pd.DataFrame({'B': [3, 4]})

In [233]:
df1

   A
0  1
1  2

In [234]:
df2

   B
0  3
1  4

In [235]:
df1 - df2

    A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

* In arithmetic operations between differently indexed objects, you might want to fill
with a special value, like 0, when an axis label is found in one object but not the other.

In [236]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [237]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [238]:
df2.loc[1, 'b'] = np.nan

In [239]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [240]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

* Adding these together results in NA values in the locations that don’t overlap.

In [241]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [242]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [243]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Using the **add** method on df1, I pass df2 and an argument to **fill_value**.

In [244]:
df1.add(df2)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [245]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

<img style="float: left;" src="pic/pic_5_5.png" width="400">

* See Table 5-5 for a listing of Series and DataFrame methods for arithmetic. 
* Each of
them has a counterpart, starting with the letter r, that has arguments flipped. 
* So these
two statements are equivalent:

In [246]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [247]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [248]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [249]:
df3 = pd.DataFrame(np.arange(10,22,2).reshape((2, 3)))

In [250]:
df4 = pd.DataFrame(np.arange(6).reshape((2, 3)))

In [251]:
df3

    0   1   2
0  10  12  14
1  16  18  20

In [252]:
df4

   0  1  2
0  0  1  2
1  3  4  5

In [253]:
df3-df4

    0   1   2
0  10  11  12
1  13  14  15

In [254]:
df3.sub(df4)

    0   1   2
0  10  11  12
1  13  14  15

In [255]:
df4.rsub(df3)

    0   1   2
0  10  11  12
1  13  14  15

Relatedly, when reindexing a Series or DataFrame, you can also specify a different fill
value.

In [256]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [257]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [258]:
df1.reindex(columns=df2.columns)

     a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

In [259]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

* As with NumPy arrays of different dimensions, arithmetic between DataFrame and
Series is also defined. 
* First, as a motivating example, consider the difference between
a two-dimensional array and one of its rows.

In [260]:
arr = np.arange(12.).reshape((3, 4))

In [261]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [262]:
arr[0]

array([0., 1., 2., 3.])

In [263]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

* When we subtract arr[0] from arr, the subtraction is performed once for each row.
* This is referred to as *broadcasting* and is explained in more detail as it relates to general
NumPy arrays in Appendix A. 
* Operations between a DataFrame and a Series are
similar.

In [264]:
df = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [265]:
series = df.iloc[0]

In [266]:
df

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [267]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

* By default, arithmetic between DataFrame and Series matches the index of the Series
on the DataFrame’s columns, broadcasting down the rows.

In [268]:
df - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

If an index value is not found in either the DataFrame’s columns or the Series’s index,
the objects will be reindexed to form the union.

In [269]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [270]:
series2

b    0
e    1
f    2
dtype: int64

In [271]:
df

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [272]:
df + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

If you want to instead broadcast over the columns, matching on the rows, you have to
use one of the arithmetic methods.

In [273]:
series3 = df['d']

In [274]:
df

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [275]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [276]:
df.sub(series3, axis='index')

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [277]:
df.sub(series3, axis=0)

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [278]:
df-series3

        Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

### Function Application and Mapping

NumPy ufuncs (element-wise array methods) also work with pandas objects.

In [279]:
df= pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [280]:
df

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [281]:
np.abs(df)

               b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

Another frequent operation is applying a function on one-dimensional arrays to each
column or row. DataFrame’s **apply** method does exactly this.

In [282]:
df

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [283]:
f = lambda x: x.max() - x.min()

In [284]:
def f(x):
    return x.max()-x.min()

In [285]:
df.apply(f)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

* Here the function f, which computes the difference between the maximum and minimum
of a Series, is invoked once on each column in frame. 
* The result is a Series having
the columns of frame as its index.
* If you pass axis='columns' to apply, the function will be invoked once per row
instead.

In [286]:
df.apply(f, axis='columns')

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

* Many of the most common array statistics (like sum and mean) are DataFrame methods,
so using apply is not necessary.
* The function passed to apply need not return a scalar value; it can also return a Series
with multiple values.

In [287]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [288]:
df.apply(f)

            b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

* Element-wise Python functions can be used, too. 
* Suppose you wanted to compute a
formatted string from each floating-point value in frame. You can do this with applymap.

In [289]:
format = lambda x: '%.2f' % x

In [290]:
df.applymap(format)

            b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

The reason for the name **applymap** is that Series has a map method for applying an
element-wise function.

In [291]:
df['e'].map(format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

### Sorting and Ranking

* Sorting a dataset by some criterion is another important built-in operation. 
* To sort
lexicographically by row or column index, use the **sort_index** method, which returns
a new, sorted object.

In [292]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [293]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [294]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

* With a DataFrame, you can sort by index on either axis.

In [295]:
df = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [296]:
df

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [297]:
df.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [298]:
df.sort_index(axis=1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

* The data is sorted in ascending order by default, but can be sorted in descending
order, too.

In [299]:
df.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

To sort a Series by its values, use its sort_values method.

In [300]:
obj = pd.Series([4, 7, -3, 2])

In [301]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [302]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

* Any missing values are sorted to the end of the Series by default.

In [303]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [304]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [305]:
obj.sort_values(ascending=False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

* When sorting a DataFrame, you can use the data in one or more columns as the sort
keys. 
* To do so, pass one or more column names to the by option of sort_values.

In [306]:
df = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [307]:
df

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [308]:
df.sort_values(by='b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

* To sort by multiple columns, pass a list of names.

In [309]:
df.sort_values(by=['a', 'b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

* *Ranking* assigns ranks from one through the number of valid data points in an array.

* The **rank** methods for Series and DataFrame are the place to look; by default **rank**
breaks ties by assigning each group the mean rank.

In [310]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [311]:
obj.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [312]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

Ranks can also be assigned according to the order in which they’re observed in the
data.

In [313]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [314]:
obj.rank(method='first').map(int)

0    6
1    1
2    7
3    4
4    3
5    2
6    5
dtype: int64

* Here, instead of using the average rank 6.5 for the entries 0 and 2, they instead have
been set to 6 and 7 because label 0 precedes label 2 in the data.


* You can rank in descending order, too:

In [315]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [316]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [317]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max').map(int)

0    2
1    7
2    2
3    4
4    5
5    6
6    4
dtype: int64

<img style="float: left;" src="pic/pic_5_6.png" width="700">

DataFrame can compute ranks over the rows or the columns.

In [318]:
df = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})

In [319]:
df

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [320]:
df.rank(axis='columns')

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

* Up until now all of the examples we’ve looked at have had unique axis labels (index
values).
* While many pandas functions (like reindex) require that the labels be
unique, it’s not mandatory.
* Let’s consider a small Series with duplicate indices.

In [321]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [322]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

The index’s **is_unique** property can tell you whether its labels are unique or not.

In [323]:
obj.index.is_unique

False

* Data selection is one of the main things that behaves differently with duplicates.
* Indexing a label with multiple entries returns a Series, while single entries return a
scalar value.

In [324]:
obj['a']

a    0
a    1
dtype: int64

In [325]:
obj['c']

4

* This can make your code more complicated, as the output type from indexing can
vary based on whether a label is repeated or not.
* The same logic extends to indexing rows in a DataFrame:

In [326]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [327]:
df

          0         1         2
a  0.274992  0.228913  1.352917
a  0.886429 -2.001637 -0.371843
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

In [328]:
df.loc['b']

          0         1         2
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

## 5.3  Summarizing and Computing Descriptive Statistics

* pandas objects are equipped with a set of common mathematical and statistical methods. 
* Most of these fall into the category of reductions or summary statistics, methods
that extract a single value (like the sum or mean) from a Series or a Series of values
from the rows or columns of a DataFrame. 
* Compared with the similar methods
found on NumPy arrays, they have built-in handling for missing data. Consider a
small DataFrame.

In [329]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [330]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Calling DataFrame’s **sum** method returns a Series containing column sums.

In [331]:
df.sum()

one    9.25
two   -5.80
dtype: float64

Passing axis='columns' or axis=1 sums across the columns instead.

In [332]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [333]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

* NA values are excluded unless the entire slice (row or column in this case) is NA.
* This can be disabled with the **skipna** option.

In [334]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [335]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

<img style="float: left;" src="pic/pic_5_7.png" width="500">

* Some methods, like **idxmin** and **idxmax**, return indirect statistics like the index value
where the minimum or maximum values are attained

In [336]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [337]:
df.idxmax()

one    b
two    d
dtype: object

Other methods are *accumulations*.

In [338]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [339]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

* Another type of method is neither a reduction nor an accumulation.   
* **describe** is one
such example, producing multiple summary statistics in one shot:

In [340]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

On non-numeric data, **describe** produces alternative summary statistics.

In [341]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [342]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [343]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

<img style="float: left;" src="pic/pic_5_8.png" width="600">

### Correlation and Covariance

생략

* Some summary statistics, like correlation and covariance, are computed from pairs of
arguments. 
* Let’s consider some DataFrames of stock prices and volumes obtained
from Yahoo! Finance using the add-on pandas-datareader package. 
* If you don’t
have it installed already, it can be obtained via conda or pip.

<p style="font-family: Courier New; font-size: 1.15em;">conda install pandas-datareader

In [ ]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

* I use the **pandas_datareader** module to download some data for a few stock tickers.

In [ ]:
import pandas_datareader.data as web

In [ ]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [ ]:
all_data

In [ ]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [ ]:
price

In [ ]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
volume

* I now compute percent changes of the prices, a time series operation which will be
explored further in Chapter 11.

In [ ]:
price.pct_change?

In [ ]:
returns = price.pct_change()

In [ ]:
returns.tail()

* The **corr** method of Series computes the correlation of the overlapping, non-NA,
aligned-by-index values in two Series. Relatedly, cov computes the covariance.

In [ ]:
returns['MSFT'].corr(returns['IBM'])

In [ ]:
returns['MSFT'].cov(returns['IBM'])

* Since MSFT is a valid Python attribute, we can also select these columns using more
concise syntax.

In [ ]:
returns.MSFT.corr(returns.IBM)

* DataFrame’s **corr** and **cov** methods, on the other hand, return a full correlation or
covariance matrix as a DataFrame, respectively.

In [ ]:
returns.corr()

In [ ]:
returns.cov()

* Using DataFrame’s **corrwith** method, you can compute pairwise correlations
between a DataFrame’s columns or rows with another Series or DataFrame. 
* Passing a
Series returns a Series with the correlation value computed for each column.

In [ ]:
returns.corrwith(returns.IBM)

* Passing a DataFrame computes the correlations of matching column names. 
* Here I
compute correlations of percent changes with volume.

In [ ]:
returns.corrwith(volume)

### Unique Values, Value Counts, and Membership

* Another class of related methods extracts information about the values contained in a
one-dimensional Series. 
* To illustrate these, consider this example.

In [344]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [345]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

The first function is **unique**, which gives you an array of the unique values in a Series.

In [346]:
uniques = obj.unique()

In [347]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [348]:
type(uniques)

numpy.ndarray

* The unique values are not necessarily returned in sorted order, but could be sorted
after the fact if needed (uniques.sort( )).

In [349]:
uniques.sort()

In [350]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

* Relatedly, **value_counts** computes a Series
containing value frequencies:

In [351]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

* The Series is sorted by value in descending order as a convenience. 
* **value_counts** is
also available as a top-level pandas method that can be used with any array or
sequence.

In [352]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [355]:
pd.value_counts(obj.values, ascending=True)

d    1
b    2
c    3
a    3
dtype: int64

이하 생략

* **isin** performs a vectorized set membership check and can be useful in filtering a
dataset down to a subset of values in a Series or column in a DataFrame.

In [356]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [357]:
mask = obj.isin(['b', 'c'])

In [358]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [359]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

* Related to **isin** is the **Index.get_indexer** method, which gives you an index array
from an array of possibly non-distinct values into another array of distinct values.

In [360]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [361]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [362]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [363]:
unique_vals

0    c
1    b
2    a
dtype: object

In [364]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

<img style="float: left;" src="pic/pic_5_9.png" width="700">